### ISSUE TITLE
Issue with deploying to Heroku from Travis

### ISSUE THREAD

**Issue by CathalButler** [CathalButler/todo-backend#2]
.travis config

```
language: node_js
node_js:
  - "16"

cache:
  directories:
    - node_modules

deploy:
  provider: heroku
  api_key:
    secure: "oux/OXGg725vu1wwL3RNzFvf5/fgl87AQ+v76deuZB7hezxWv8ZZ3C1L1V6F8eqpg0r3rUsKfAwDgpki0Ov+cqlgjdkZ/m1wbbduJtN2phGrwW5QyvmufCM/hf3nWPxEl5FaKalp9wTffhfeVYzqIulKyghWaO/EUL8m1POm3PZ4mtAFH248yRTN9K2dFWrY6fgyWRQqcRXoSX9vb/3c/yj7OPFhoktP/LOiLCgQR4yqnowDo651OCvXu3ZStFiRA0xzbAsDzWuEFog0OQC/LCfbdKuZeQi0rgSk4ZQb2nURua4RG/Rpw8312mfrRAXn/JZYghVtydxjKKaoAo/dTbfvk54WR4QVpQwCCAruTKvNDpPiOu4M2WebTa0fri7/aG2FdCPrRcdb0EXdhwKKINn1yyW3BEGh9+KJns4dxxMeK4zwony8ze+BjlxIPPaPUThz6A4FI5qPVQ5cXEejwiDskQs8x4WeTD7DFedcChdilv8PPsVeRMOXw2Ev4VrvNxlTW3jieM50pmqe/dGtt0BglXhEl6U18VrnV8pUilQSMzHlPdJwto4wCgnJAffFNO1J36f5W+eQHWnTNZILlp5+3PA5zUrK6IcgJblWfwrqEUdGS0eyLORtyITFa4szAEoS/1QfyPKlsk4UmBgMjh0DOeIWydxRSJUCCdKDjko="
  app: todo-backend
  on:
    branch: main
```

Job output:

```
ERROR:  Error installing dpl-heroku:
	The last version of faraday-net_http (>= 2.0, < 3.1) to support your Ruby & RubyGems was 2.1.0. Try installing it with `gem install faraday-net_http -v 2.1.0` and then running the current command again
	faraday-net_http requires Ruby version >= 2.6.0. The current ruby version is 2.4.5.335.
/home/travis/.rvm/rubies/ruby-2.4.5/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- dpl/provider/heroku (LoadError)
	from /home/travis/.rvm/rubies/ruby-2.4.5/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.16/lib/dpl/provider.rb:93:in `rescue in block in new'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.16/lib/dpl/provider.rb:68:in `block in new'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.16/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.16/lib/dpl/provider.rb:67:in `new'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.16/lib/dpl/cli.rb:31:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.16/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.16/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.4.5/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.4.5/bin/dpl:23:in `<main>'
```

https://github.com/travis-ci/dpl/issues/1247
